less verbose now its quintessentially AWESOME

diff --git a/bin/ok b/bin/ok
--- a/bin/ok
+++ b/bin/ok
@@ -3,6 +3,7 @@
 FILE=`mktemp -t okidok.XXXXX`
 LOGFILE=/var/log/riccardo/ok.log
 touch "$LOGFILE"
+DEBUG=false
 
 # logs and prints output!
 oklog() {
@@ -13,12 +14,12 @@ oklog() {
 oklog "Started with args: '$*'"
 
 if [ "$1" = '-' ] ; then
- echo 'Called ok with -, assuming STDIN!'	>&2
- oklog "called from stdin"
- cat | ricnotify yellow "OK from STDIN '$*'"
- RET=$?
- oklog "End STDIN RET=$RET for: '$*'"
- exit $RET
+	echo 'Called ok with -, assuming STDIN!'	>&2
+	oklog "called from stdin"
+	cat | ricnotify yellow "OK from STDIN '$*'"
+	RET=$?
+	oklog "End STDIN RET=$RET for: '$*'"
+	exit $RET
 fi
 
 echo "`data` Start '$*'"
@@ -30,13 +31,13 @@ RET=$PIPESTATUS
 MSG=_NONE_
 
 if [ 0 = $RET ] ; then
-	verde "👍 OK: $*"
-	tail -20 "$FILE" | ricnotify green "OK '$*'"
-	echo "`data` End OK"
+	verde "👍 OK(`data`): $*"
+	#tail -20 "$FILE" | ricnotify green "OK '$*'"
+	#echo "`data` End OK"
 else
-	rosso "👎 NO(ret=$RET): $*"
-	echo "`data` End (ERR) '$*'"
-	echo "There were some errors which returned: $RET" | ricnotify red "Err with '$*'"
+	rosso "👎 NO(`data`,ret=$RET): $*"
+	#echo "`data` End (ERR) '$*'"
+	#echo "There were some errors which returned: $RET" | ricnotify red "Err with '$*'"
 fi
-oklog "End $MSG($RET): '$*'"
+oklog "End $MSG($RET): '$*'" >/dev/null
 exit $RET
